import type { Template } from './types'

export const templates: Template[] = [
  // ── 1. Bold Quote ────────────────────────────────────────
  {
    id: 'bold-quote',
    name: 'Bold Quote',
    format: 'ig-post',
    previewColors: ['#1a1a2e', '#16213e'],
    canvas: {
      width: 1080,
      height: 1080,
      backgroundColor: '#1a1a2e',
      elements: [
        {
          id: 'bq-line',
          type: 'shape',
          shapeType: 'rect',
          x: 440,
          y: 280,
          width: 200,
          height: 4,
          rotation: 0,
          opacity: 0.8,
          locked: false,
          fill: '#7c3aed',
          cornerRadius: 2,
        },
        {
          id: 'bq-quote',
          type: 'text',
          x: 120,
          y: 340,
          width: 840,
          height: 300,
          rotation: 0,
          opacity: 1,
          locked: false,
          text: 'Your inspiring\nquote goes here.',
          fontSize: 72,
          fontFamily: 'Montserrat',
          fontWeight: 700,
          fill: '#ffffff',
          align: 'center',
          lineHeight: 1.2,
        },
        {
          id: 'bq-attr',
          type: 'text',
          x: 120,
          y: 720,
          width: 840,
          height: 60,
          rotation: 0,
          opacity: 0.5,
          locked: false,
          text: '@yourbrand',
          fontSize: 28,
          fontFamily: 'Inter',
          fontWeight: 400,
          fill: '#ffffff',
          align: 'center',
        },
      ],
    },
  },

  // ── 2. Gradient Story ────────────────────────────────────
  {
    id: 'gradient-story',
    name: 'Gradient Story',
    format: 'ig-story',
    previewColors: ['#667eea', '#764ba2'],
    canvas: {
      width: 1080,
      height: 1920,
      backgroundColor: '#667eea',
      elements: [
        {
          id: 'gs-bg',
          type: 'shape',
          shapeType: 'rect',
          x: 0,
          y: 960,
          width: 1080,
          height: 960,
          rotation: 0,
          opacity: 0.6,
          locked: true,
          fill: '#764ba2',
        },
        {
          id: 'gs-heading',
          type: 'text',
          x: 80,
          y: 400,
          width: 920,
          height: 300,
          rotation: 0,
          opacity: 1,
          locked: false,
          text: 'YOUR BIG\nHEADLINE',
          fontSize: 84,
          fontFamily: 'Montserrat',
          fontWeight: 900,
          fill: '#ffffff',
          align: 'left',
          lineHeight: 1.1,
        },
        {
          id: 'gs-sub',
          type: 'text',
          x: 80,
          y: 740,
          width: 920,
          height: 100,
          rotation: 0,
          opacity: 0.7,
          locked: false,
          text: 'Supporting text goes here\nwith more details.',
          fontSize: 32,
          fontFamily: 'Inter',
          fontWeight: 400,
          fill: '#ffffff',
          align: 'left',
          lineHeight: 1.5,
        },
        {
          id: 'gs-cta',
          type: 'shape',
          shapeType: 'rect',
          x: 80,
          y: 1600,
          width: 400,
          height: 80,
          rotation: 0,
          opacity: 1,
          locked: false,
          fill: '#ffffff',
          cornerRadius: 40,
        },
        {
          id: 'gs-cta-text',
          type: 'text',
          x: 80,
          y: 1616,
          width: 400,
          height: 48,
          rotation: 0,
          opacity: 1,
          locked: false,
          text: 'SWIPE UP',
          fontSize: 24,
          fontFamily: 'Montserrat',
          fontWeight: 700,
          fill: '#764ba2',
          align: 'center',
        },
      ],
    },
  },

  // ── 3. Clean Split ───────────────────────────────────────
  {
    id: 'clean-split',
    name: 'Clean Split',
    format: 'ig-post',
    previewColors: ['#7c3aed', '#ffffff'],
    canvas: {
      width: 1080,
      height: 1080,
      backgroundColor: '#ffffff',
      elements: [
        {
          id: 'cs-left',
          type: 'shape',
          shapeType: 'rect',
          x: 0,
          y: 0,
          width: 480,
          height: 1080,
          rotation: 0,
          opacity: 1,
          locked: false,
          fill: '#7c3aed',
        },
        {
          id: 'cs-title',
          type: 'text',
          x: 540,
          y: 380,
          width: 460,
          height: 150,
          rotation: 0,
          opacity: 1,
          locked: false,
          text: 'Title Goes\nRight Here',
          fontSize: 48,
          fontFamily: 'Montserrat',
          fontWeight: 700,
          fill: '#1a1a2e',
          align: 'left',
          lineHeight: 1.2,
        },
        {
          id: 'cs-body',
          type: 'text',
          x: 540,
          y: 560,
          width: 460,
          height: 100,
          rotation: 0,
          opacity: 0.6,
          locked: false,
          text: 'A brief description or\nsubheading for context.',
          fontSize: 24,
          fontFamily: 'Inter',
          fontWeight: 400,
          fill: '#1a1a2e',
          align: 'left',
          lineHeight: 1.5,
        },
      ],
    },
  },

  // ── 4. Minimal Card ──────────────────────────────────────
  {
    id: 'minimal-card',
    name: 'Minimal Card',
    format: 'ig-post',
    previewColors: ['#fafafa', '#e5e5e5'],
    canvas: {
      width: 1080,
      height: 1080,
      backgroundColor: '#fafafa',
      elements: [
        {
          id: 'mc-border',
          type: 'shape',
          shapeType: 'rect',
          x: 60,
          y: 60,
          width: 960,
          height: 960,
          rotation: 0,
          opacity: 1,
          locked: true,
          fill: 'transparent',
          stroke: '#d4d4d4',
          strokeWidth: 2,
          cornerRadius: 0,
        },
        {
          id: 'mc-title',
          type: 'text',
          x: 120,
          y: 420,
          width: 840,
          height: 80,
          rotation: 0,
          opacity: 1,
          locked: false,
          text: 'MINIMAL',
          fontSize: 64,
          fontFamily: 'Montserrat',
          fontWeight: 300,
          fill: '#262626',
          align: 'center',
        },
        {
          id: 'mc-sub',
          type: 'text',
          x: 120,
          y: 520,
          width: 840,
          height: 60,
          rotation: 0,
          opacity: 0.5,
          locked: false,
          text: 'Clean & Simple',
          fontSize: 28,
          fontFamily: 'Inter',
          fontWeight: 400,
          fill: '#262626',
          align: 'center',
        },
      ],
    },
  },

  // ── 5. Dark Banner ───────────────────────────────────────
  {
    id: 'dark-banner',
    name: 'Dark Banner',
    format: 'fb-post',
    previewColors: ['#0f0f0f', '#7c3aed'],
    canvas: {
      width: 1200,
      height: 630,
      backgroundColor: '#0f0f0f',
      elements: [
        {
          id: 'db-accent',
          type: 'shape',
          shapeType: 'rect',
          x: 0,
          y: 580,
          width: 1200,
          height: 50,
          rotation: 0,
          opacity: 0.8,
          locked: true,
          fill: '#7c3aed',
        },
        {
          id: 'db-title',
          type: 'text',
          x: 80,
          y: 200,
          width: 1040,
          height: 100,
          rotation: 0,
          opacity: 1,
          locked: false,
          text: 'Announcement Title',
          fontSize: 56,
          fontFamily: 'Montserrat',
          fontWeight: 700,
          fill: '#ffffff',
          align: 'left',
        },
        {
          id: 'db-sub',
          type: 'text',
          x: 80,
          y: 320,
          width: 800,
          height: 80,
          rotation: 0,
          opacity: 0.6,
          locked: false,
          text: 'A brief description of what this is about.',
          fontSize: 28,
          fontFamily: 'Inter',
          fontWeight: 400,
          fill: '#ffffff',
          align: 'left',
          lineHeight: 1.5,
        },
      ],
    },
  },

  // ── 6. Carousel Slide ────────────────────────────────────
  {
    id: 'carousel-slide',
    name: 'Carousel Slide',
    format: 'carousel',
    previewColors: ['#f8f9fa', '#06b6d4'],
    canvas: {
      width: 1080,
      height: 1080,
      backgroundColor: '#f8f9fa',
      elements: [
        {
          id: 'car-num-bg',
          type: 'shape',
          shapeType: 'circle',
          x: 490,
          y: 180,
          width: 100,
          height: 100,
          rotation: 0,
          opacity: 1,
          locked: false,
          fill: '#06b6d4',
        },
        {
          id: 'car-num',
          type: 'text',
          x: 490,
          y: 200,
          width: 100,
          height: 60,
          rotation: 0,
          opacity: 1,
          locked: false,
          text: '01',
          fontSize: 36,
          fontFamily: 'Montserrat',
          fontWeight: 700,
          fill: '#ffffff',
          align: 'center',
        },
        {
          id: 'car-title',
          type: 'text',
          x: 120,
          y: 360,
          width: 840,
          height: 100,
          rotation: 0,
          opacity: 1,
          locked: false,
          text: 'Slide Title Here',
          fontSize: 52,
          fontFamily: 'Montserrat',
          fontWeight: 700,
          fill: '#1a1a2e',
          align: 'center',
        },
        {
          id: 'car-body',
          type: 'text',
          x: 160,
          y: 500,
          width: 760,
          height: 200,
          rotation: 0,
          opacity: 0.6,
          locked: false,
          text: 'Add your content here.\nKeep it concise and\neasy to read on mobile.',
          fontSize: 28,
          fontFamily: 'Inter',
          fontWeight: 400,
          fill: '#1a1a2e',
          align: 'center',
          lineHeight: 1.6,
        },
      ],
    },
  },
]
